kind: Service
apiVersion: v1
metadata:
  name: topsecret-prod
spec:
  selector:
    app: topsecret-prod
  ports:
  - name: http
    protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topsecret-prod
  labels:
    app: topsecret-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topsecret-prod
  template:
    metadata:
      labels:
        app: topsecret-prod
    spec:
     containers:
      - name: topsecret-prod
        image: reg.foobz.com.au/apps/blindfold-app
        #imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: inputjson
          mountPath: /usr/src/app/input.json
          subPath: input.json
     volumes:
       - name: inputjson
         configMap:
           name: my-blindfold-secret